// src/redux/courseSlice.js
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  courses: [
  {
    id: 1,
    title: "Python Full Stack",
    description: "Learn Python, Django, and modern frontend tools.",
    overview:
      "This comprehensive Python Full Stack course is designed to take you from a beginner to a proficient full-stack developer. You will master Python programming, backend development using Django, and frontend technologies such as HTML, CSS, and JavaScript. The course also covers database management, RESTful APIs, and modern frontend frameworks, giving you the skills to build robust, dynamic web applications. With hands-on projects and real-world examples, you will gain practical experience and a portfolio to showcase your abilities.",
    students: 1500,
    duration: "6 Months",
    rating: "4.7",
    category: "Web Development",
    salary: "₹5–10 LPA",
    tools: ["Python", "Django", "SQLite", "HTML", "CSS", "JavaScript", "React", "Git"],
    roles: ["Full Stack Developer", "Backend Developer", "Web Developer", "Software Engineer"],
    image: "https://qicon.in/wp-content/uploads/2023/04/WhatsApp-Image-2023-04-05-at-6.11.42-PM.jpeg",
    comingSoon: null,
    video: null,
    syllabus: [
      { title: "Python Basics", description: "Syntax, variables, data types, control flow, functions" },
      { title: "Object-Oriented Programming", description: "Classes, objects, inheritance, polymorphism" },
      { title: "Database Integration", description: "MySQL/SQLite, CRUD operations with Python" },
      { title: "Web Development with Flask/Django", description: "Building web apps, templates, routing, authentication" },
      { title: "Frontend Development", description: "HTML, CSS, JavaScript, React basics" },
      { title: "REST APIs", description: "Creating and consuming APIs, JWT authentication" },
      { title: "Deployment & DevOps Basics", description: "Docker, Git/GitHub, CI/CD, deployment on cloud" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 2,
    title: "MERN Stack Development",
    description: "Master MongoDB, Express, React, and Node.",
    overview:
      "The MERN Stack course equips you with the skills to become a full-stack web developer using MongoDB, Express.js, React.js, and Node.js. You will learn to build dynamic, scalable web applications from scratch, covering both frontend and backend development. The course includes hands-on projects, RESTful APIs, state management, and deployment strategies, ensuring you gain practical experience in building real-world applications. By the end, you’ll have a strong portfolio and the confidence to work as a MERN Stack developer.",
    students: 2000,
    duration: "5 Months",
    rating: "4.6",
    category: "Web Development",
    salary: "₹6–12 LPA",
    tools: ["MongoDB", "Express.js", "React.js", "Node.js", "Redux", "Postman", "Git", "Vercel"],
    roles: ["MERN Stack Developer", "Frontend Developer", "Backend Developer", "Web Application Engineer"],
    image: "https://images.prismic.io/loco-blogs/79328284-f97b-489f-924c-eb3b17e34b56_image2.png?auto=compress%2Cformat&rect=0%2C0%2C1999%2C1124&w=1920&h=1080&ar=1.91%3A1",
    comingSoon: null,
    video: null,
    syllabus: [
      { title: "Introduction to React", description: "Overview of React, components, and JSX" },
      { title: "Props and State", description: "Passing data with props, managing state effectively" },
      { title: "Hooks", description: "Using useState, useEffect, and custom hooks" },
      { title: "Routing", description: "React Router, navigation, and dynamic routes" },
      { title: "Forms & Validation", description: "Controlled components, form handling, and validation" },
      { title: "State Management", description: "Context API and Redux basics" },
      { title: "Project", description: "Building a small React project with all concepts" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 3,
    title: "Data Analysis",
    description: "Learn data wrangling, visualization, and ML basics.",
    overview:
      "This Data Analysis course is designed to equip you with the skills to interpret, visualize, and derive insights from complex datasets. You will learn essential tools and techniques, including Python, Pandas, NumPy, Matplotlib, and data cleaning methods. The course also covers exploratory data analysis, statistical concepts, and real-world case studies, enabling you to make data-driven decisions. By the end, you will be able to analyze data effectively and present actionable insights for business or research purposes.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Data Analysis",
    salary: "₹4–9 LPA",
    tools: ["Python", "Pandas", "NumPy", "Matplotlib", "Power BI", "Excel", "Jupyter", "SQL"],
    roles: ["Data Analyst", "Business Analyst", "Reporting Analyst", "Junior Data Scientist"],
    image: "https://wallpaperaccess.com/full/3457552.jpg",
    syllabus: [
      { title: "Introduction to Data Analysis", description: "Understanding data, types, and sources" },
      { title: "Data Cleaning", description: "Handling missing values, duplicates, and outliers" },
      { title: "Exploratory Data Analysis", description: "Using statistics and visualization to understand data" },
      { title: "Data Visualization", description: "Charts, plots, and dashboards with Python libraries" },
      { title: "Data Wrangling", description: "Merging, joining, and transforming datasets" },
      { title: "Basic Machine Learning", description: "Introduction to regression, classification, and clustering" },
      { title: "Project", description: "Analyzing a real-world dataset and presenting insights" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 4,
    title: "Graphic Designing",
    description: "UI/UX design, Adobe tools, and modern design trends.",
    overview:
      "This Graphics Design course is crafted to help you unleash your creativity and master visual communication. You will learn essential design principles, color theory, typography, and composition, along with hands-on skills in tools like Adobe Photoshop, Illustrator, and Canva. The course covers creating logos, social media graphics, banners, and other digital assets, enabling you to design professional-quality visuals. By the end, you’ll have a strong portfolio and the confidence to work as a graphic designer in various creative fields.",
    students: 800,
    duration: "3 Months",
    rating: "4.5",
    category: "UI/UX",
    salary: "₹3–8 LPA",
    tools: ["Adobe Photoshop", "Illustrator", "Canva", "Figma", "InDesign", "XD"],
    roles: ["Graphic Designer", "UI Designer", "Visual Artist", "Brand Identity Designer"],
    image: "https://clipart-library.com/images/rTjrn5Lkc.jpg",
    syllabus: [
      { title: "Introduction to Graphic Design", description: "Understanding design principles, elements, and tools" },
      { title: "Typography", description: "Fonts, hierarchy, readability, and design with text" },
      { title: "Color Theory", description: "Psychology of colors, color harmony, and palettes" },
      { title: "Adobe Photoshop", description: "Image editing, photo manipulation, and digital artwork" },
      { title: "Adobe Illustrator", description: "Vector graphics, logos, and illustrations" },
      { title: "Layout & Composition", description: "Balance, alignment, grids, and whitespace" },
      { title: "Branding & Identity Design", description: "Logos, brand guidelines, and visual identity" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 6,
    title: "Digital Marketing",
    description: "Master Digital Marketing from fundamentals to advanced strategies.",
    overview:
      "This Digital Marketing course provides a complete understanding of modern online marketing strategies. You will learn SEO, social media marketing, email campaigns, content marketing, PPC advertising, and analytics tools to measure performance. The course combines theory with practical projects, enabling you to create effective marketing campaigns, grow online presence, and drive business results. By the end, you’ll be equipped to plan, execute, and optimize digital marketing strategies like a professional.",
    students: 950,
    duration: "3 Months",
    rating: "4.7",
    category: "Marketing",
    salary: "₹4–9 LPA",
    tools: ["Google Ads", "Canva", "Meta Business Suite", "Google Analytics", "Ahrefs", "Mailchimp"],
    roles: ["Digital Marketer", "SEO Specialist", "Content Strategist", "Social Media Manager"],
    image:
      "https://img.freepik.com/free-photo/digital-marketing-with-icons-business-people_53876-94833.jpg?semt=ais_hybrid&w=740&q=80",
    syllabus: [
      { title: "Introduction to Digital Marketing", description: "Introduction to Digital Marketing – ecosystem, trends, and strategy" },
      { title: "Traditional vs. Digital Marketing", description: "Understanding the evolution of marketing" },
      { title: "Website Planning & Development", description: "Domains, hosting, WordPress, and no-code tools" },
      { title: "SEO", description: "On-page, off-page, and technical SEO" },
      { title: "Social Media Marketing", description: "Facebook, Instagram, LinkedIn, YouTube advertising" },
      { title: "Content Marketing", description: "Blogging, videos, infographics, and storytelling" },
      { title: "Google Analytics 4 (GA4)", description: "Goals, events, and conversion tracking" },
      { title: "Capstone Project", description: "Design and execute a real campaign" },
    ],
    createdAt: "2025-08-28T01:03:09.000Z",
  },
  {
    id: 7,
    title: "Cybersecurity Essentials",
    description:
      "Gain hands-on skills in cybersecurity fundamentals, threats, risk management, cryptography, and incident response.",
    overview:
      "The Cybersecurity Essentials course is designed to provide a solid foundation in protecting digital systems and data. You will learn key concepts such as network security, threat detection, encryption, ethical hacking, and risk management. The course includes hands-on exercises and real-world scenarios to help you understand vulnerabilities and implement effective security measures. By the end, you will have the skills to safeguard information systems and pursue further specialization in cybersecurity.",
    students: 870,
    duration: "3 Months",
    rating: "4.8",
    category: "Cyber",
    salary: "₹6–14 LPA",
    tools: ["Wireshark", "Kali Linux", "Metasploit", "Burp Suite", "Nmap", "Splunk"],
    roles: ["Cybersecurity Analyst", "Ethical Hacker", "Network Security Engineer", "SOC Analyst"],
    image: "https://www.bitlyft.com/hubfs/Cybersecurity-solutions.jpeg",
    syllabus: [
      { title: "Introduction to Cybersecurity", description: "Principles and core concepts of cybersecurity" },
      { title: "Cyber Threats and Attack Types", description: "Understanding malware, phishing, ransomware" },
      { title: "Scanning and Vulnerability Assessment", description: "Techniques and tools for scanning networks" },
      { title: "Incident Response", description: "Detecting, managing, and mitigating security breaches" },
      { title: "Cryptography Fundamentals", description: "Encryption, decryption, symmetric/asymmetric keys" },
      { title: "System and Network Hardening", description: "Securing servers and network devices" },
    ],
    createdAt: "2025-08-28T23:03:09.000Z",
  },
  {
    id: 8,
    title: "Game Development in Python",
    description: "Build real-world games using Python libraries like Pygame.",
    overview:
      "This Game Development in Python course teaches you how to create engaging 2D and interactive games using Python and popular libraries like Pygame. You will learn programming fundamentals, game mechanics, animation, collision detection, and user input handling, along with tips for designing fun and playable games. Through hands-on projects, you will build complete games from scratch, gaining practical experience and a portfolio to showcase your game development skills.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Game Development",
    salary: "₹4–8 LPA",
    tools: ["Python", "Pygame", "Blender", "Unity (basics)", "Git"],
    roles: ["Game Developer", "Python Developer", "Indie Game Creator", "Gameplay Programmer"],
    image: "https://t4.ftcdn.net/jpg/03/53/67/99/360_F_353679927_RaLUr71JJfKlGCbbchpuSYc402OxP3hg.jpg",
    syllabus: [
      { title: "Introduction to Game Development", description: "Understanding game design principles" },
      { title: "Python Fundamentals for Gaming", description: "Learn Python syntax and logic for games" },
      { title: "Getting Started with Pygame", description: "Introduction to Pygame library" },
      { title: "Game Mechanics & Controls", description: "Handling keyboard/mouse inputs, collisions" },
      { title: "Graphics, Animation & Sound", description: "Integrating sprites, backgrounds, and audio" },
      { title: "Mini Projects", description: "Build games like Snake, Flappy Bird, or Space Shooter" },
      { title: "Game Deployment", description: "Exporting games as executables" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 9,
    title: "Software Development",
    description: "Master the art of building scalable, efficient software systems.",
    overview:
      "The Software Development course provides a complete foundation for building modern software applications. You will learn programming fundamentals, software design principles, development methodologies, debugging, and testing. The course also covers both frontend and backend development, databases, and version control, giving you the practical skills to create efficient, scalable, and maintainable software. By the end, you’ll be prepared to develop real-world applications and start your career as a software developer.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Software Development",
    salary: "₹6–12 LPA",
    tools: ["Python", "Java", "Git", "MySQL", "VS Code", "Docker", "Postman"],
    roles: ["Software Developer", "Application Developer", "Backend Engineer", "Junior Software Engineer"],
    image: "https://initialcommit.com/img/initialcommit/how-to-be-a-software-developer.jpg",
    syllabus: [
      { title: "Programming Fundamentals", description: "Core programming concepts and logic building" },
      { title: "Software Design", description: "OOPs, design patterns, and best practices" },
      { title: "Frontend & Backend Development", description: "End-to-end app creation and integration" },
      { title: "Testing & Debugging", description: "Automated testing and bug resolution" },
      { title: "Database & APIs", description: "Working with relational databases and REST APIs" },
      { title: "Version Control & Deployment", description: "Git, CI/CD, and application deployment" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
],

   workshops: [
    {
      id: 1,
      title: "Data Science",
      description: "Your Fast Track to a High-Demand Career!",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_7zWRQPxwM5OcZbrb-JKgqmBZUshShzt17A&s",
      registered: "80K+ Registered",
      rating: "4.5",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 2,
      title: "React Native Mobile App",
      description: "Learn to build cross-platform mobile apps with React Native.",
      image: "https://images.ctfassets.net/aq13lwl6616q/2gqVi4hhjq9vgvdh63UoKZ/0366c66ecd9f9e928745231d061dbb56/react_native_zero_to_mastery.png",
      registered: "50K+ Registered",
      rating: "4.8",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 3,
      title: "UI/UX Design",
      description: "Master the fundamentals of UI/UX and create stunning interfaces.",
      image: "https://www.almondsolutions.com/images/blog-ui-ux-150223.jpg",
      registered: "70K+ Registered",
      rating: "4.7",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
  ],
  workshops: [
    {
      id: 1,
      title: "Data Science",
      description: "Your Fast Track to a High-Demand Career!",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_7zWRQPxwM5OcZbrb-JKgqmBZUshShzt17A&s",
      registered: "80K+ Registered",
      rating: "4.5",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 2,
      title: "React Native Mobile App",
      description: "Learn to build cross-platform mobile apps with React Native.",
      image:
        "https://images.ctfassets.net/aq13lwl6616q/2gqVi4hhjq9vgvdh63UoKZ/0366c66ecd9f9e928745231d061dbb56/react_native_zero_to_mastery.png",
      registered: "50K+ Registered",
      rating: "4.8",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 3,
      title: "UI/UX Design",
      description: "Master the fundamentals of UI/UX and create stunning interfaces.",
      image:
        "https://www.almondsolutions.com/images/blog-ui-ux-150223.jpg",
      registered: "70K+ Registered",
      rating: "4.7",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
  ],

  mentors: [
    {
      id: 3,
      name: "Pranav Swaroop",
      role: "Cyber Security",
      image: "https://i.postimg.cc/brPCnxkr/IMG-20251025-194531-757.webp",
      linkedin: "https://www.linkedin.com/in/pranav-swaroop-75671317?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ",
    },
    {
      id: 4,
      name: "Vasudha",
      role: "Data Analysis",
      image: "https://i.postimg.cc/pLNdNyfz/dha-removebg-preview.png",
      linkedin: "#",
    },
    {
      id: 5,
      name: "Shanthini",
      role: "MERN Stack",
      image: "https://i.postimg.cc/dV36rgL0/Shan.jpg",
      linkedin: "#",
    },
    {
      id: 6,
      name: "Hari Prasadh",
      role: "Digital Marketing",
      image: "https://i.postimg.cc/6pqcnFy4/Harrii.jpg",
      linkedin: "#",
    },
    {
      id: 7,
      name: "Priya Dharshini",
      role: "Python Full Stack",
      image: "https://i.postimg.cc/YqZg4PjR/priya.jpg",
      linkedin: "#",
    },
    {
      id: 8,
      name: "Karthik Raja",
      role: "Cybersecurity Essentials",
      image: "https://i.postimg.cc/BQTvDYbM/karthik.jpg",
      linkedin: "#",
    },
    {
      id: 9,
      name: "Divya Lakshmi",
      role: "Graphics Design",
      image: "https://i.postimg.cc/76L0zdw5/divya.jpg",
      linkedin: "#",
    },
    {
      id: 10,
      name: "Vignesh Kumar",
      role: "Game Development in Python",
      image: "https://i.postimg.cc/HnmJc6vP/vignesh.jpg",
      linkedin: "#",
    },
    {
      id: 11,
      name: "Monisha",
      role: "Software Development",
      image: "https://i.postimg.cc/g0WkJ2fK/monisha.jpg",
      linkedin: "#",
    },
    {
      id: 12,
      name: "Sathish Kumar",
      role: "MERN Stack",
      image: "https://i.postimg.cc/X7CnG0fM/sathish.jpg",
      linkedin: "#",
    },
  ],
};

const courseSlice = createSlice({
  name: "courses",
  initialState,
  reducers: {
    addCourse: (state, action) => {
      state.courses.push(action.payload);
    },
    addWorkshop: (state, action) => {
      state.workshops.push(action.payload);
    },
  },
});

export const { addCourse, addWorkshop } = courseSlice.actions;
export default courseSlice.reducer;

