// src/redux/courseSlice.js
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  courses: [
  {
    id: 1,
    title: "Python Full Stack",
    description: "Learn Python, Django, and modern frontend tools.",
    overview:
      "This comprehensive Python Full Stack course is designed to take you from a beginner to a proficient full-stack developer. You will master Python programming, backend development using Django, and frontend technologies such as HTML, CSS, and JavaScript. The course also covers database management, RESTful APIs, and modern frontend frameworks, giving you the skills to build robust, dynamic web applications. With hands-on projects and real-world examples, you will gain practical experience and a portfolio to showcase your abilities.",
    students: 1500,
    duration: "6 Months",
    rating: "4.7",
    category: "Web Development",
    salary: "₹5–10 LPA",
    tools: ["Python", "Django", "SQLite", "HTML", "CSS", "JavaScript", "React", "Git"],
    roles: ["Full Stack Developer", "Backend Developer", "Web Developer", "Software Engineer"],
  
    image: "https://digitalwinacademics.com/wp-content/uploads/2024/06/python-2-768x431.jpg",
    comingSoon: null,
    video: null,
    syllabus: [
      { title: "Python Basics", description: "Syntax, variables, data types, control flow, functions" },
      { title: "Object-Oriented Programming", description: "Classes, objects, inheritance, polymorphism" },
      { title: "Database Integration", description: "MySQL/SQLite, CRUD operations with Python" },
      { title: "Web Development with Flask/Django", description: "Building web apps, templates, routing, authentication" },
      { title: "Frontend Development", description: "HTML, CSS, JavaScript, React basics" },
      { title: "REST APIs", description: "Creating and consuming APIs, JWT authentication" },
      { title: "Deployment & DevOps Basics", description: "Docker, Git/GitHub, CI/CD, deployment on cloud" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 2,
    title: "MERN Stack Development",
    description: "Master MongoDB, Express, React, and Node.",
    overview:
      "The MERN Stack course equips you with the skills to become a full-stack web developer using MongoDB, Express.js, React.js, and Node.js. You will learn to build dynamic, scalable web applications from scratch, covering both frontend and backend development. The course includes hands-on projects, RESTful APIs, state management, and deployment strategies, ensuring you gain practical experience in building real-world applications. By the end, you’ll have a strong portfolio and the confidence to work as a MERN Stack developer.",
    students: 2000,
    duration: "5 Months",
    rating: "4.6",
    category: "Web Development",
    salary: "₹6–12 LPA",
    tools: ["MongoDB", "Express.js", "React.js", "Node.js", "Redux", "Postman", "Git", "Vercel"],
    roles: ["MERN Stack Developer", "Frontend Developer", "Backend Developer", "Web Application Engineer"],
    image: "https://i.pinimg.com/736x/92/40/8e/92408e6e22f4d02cf2344287814ee257.jpg",
    comingSoon: null,
    video: null,
    syllabus: [
      { title: "Introduction to React", description: "Overview of React, components, and JSX" },
      { title: "Props and State", description: "Passing data with props, managing state effectively" },
      { title: "Hooks", description: "Using useState, useEffect, and custom hooks" },
      { title: "Routing", description: "React Router, navigation, and dynamic routes" },
      { title: "Forms & Validation", description: "Controlled components, form handling, and validation" },
      { title: "State Management", description: "Context API and Redux basics" },
      { title: "Project", description: "Building a small React project with all concepts" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
  id: 3,
  title: "Java Full Stack Development",
  description: "Master backend with Java & Spring Boot and frontend with React to build enterprise applications.",
  overview:
    "This course provides full-stack development expertise using Java, Spring Boot, MySQL, and React.js. You will learn OOP, REST API development, authentication, deployment, and industry-standard backend architecture. On the frontend, you'll build interactive UI using React, Redux, and Tailwind. Real-time projects include e-commerce systems, admin dashboards, and authentication modules. By the end, you'll be job-ready for enterprise-level full-stack roles.",
  students: 1200,
  duration: "6 Months",
  rating: "4.8",
  category: "Web Development",
  salary: "₹6–15 LPA",
  tools: ["Java", "Spring Boot", "Hibernate", "MySQL", "React.js", "Git", "Postman", "Docker (Basics)"],
  roles: [
    "Java Full-Stack Developer",
    "Backend Developer (Java)",
    "Software Engineer",
    "Web Application Developer"
  ],
  
  image: "https://i.pinimg.com/1200x/48/27/12/4827123b437699a9ba8e8feb1537e255.jpg",
  syllabus: [
    { title: "Core Java & OOP", description: "Java basics, OOP concepts, collections, exception handling" },
    { title: "Spring Boot & API Development", description: "REST APIs, MVC, JPA, security & JWT authentication" },
    { title: "Database & ORM", description: "MySQL, Hibernate, schema design, queries & joins" },
    { title: "React Frontend Development", description: "Components, hooks, routing, Redux & UI development" },
    { title: "Full Stack Integration", description: "Connecting React frontend with Spring Boot backend" },
    { title: "Deployment & DevOps Basics", description: "Git, CI/CD basics, Docker introduction & hosting" }
  ],
  createdAt: "2025-08-27T14:03:09.000Z",
},
{
    id: 4,
    title: "Data Analysis",
    description: "Learn data wrangling, visualization, and ML basics.",
    overview:
      "This Data Analysis course is designed to equip you with the skills to interpret, visualize, and derive insights from complex datasets. You will learn essential tools and techniques, including Python, Pandas, NumPy, Matplotlib, and data cleaning methods. The course also covers exploratory data analysis, statistical concepts, and real-world case studies, enabling you to make data-driven decisions. By the end, you will be able to analyze data effectively and present actionable insights for business or research purposes.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Data Analysis",
    salary: "₹4–9 LPA",
    tools: ["Python", "Pandas", "NumPy", "Matplotlib", "Power BI", "Excel", "Jupyter", "SQL"],
    roles: ["Data Analyst", "Business Analyst", "Reporting Analyst", "Junior Data Scientist"],
    image: "https://i.pinimg.com/1200x/b2/ac/d2/b2acd28d6bb47ab01eb664d52b6ad2d8.jpg",
    syllabus: [
      { title: "Introduction to Data Analysis", description: "Understanding data, types, and sources" },
      { title: "Data Cleaning", description: "Handling missing values, duplicates, and outliers" },
      { title: "Exploratory Data Analysis", description: "Using statistics and visualization to understand data" },
      { title: "Data Visualization", description: "Charts, plots, and dashboards with Python libraries" },
      { title: "Data Wrangling", description: "Merging, joining, and transforming datasets" },
      { title: "Basic Machine Learning", description: "Introduction to regression, classification, and clustering" },
      { title: "Project", description: "Analyzing a real-world dataset and presenting insights" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  { 
    id: 5,
    title: "Graphic Designing",
    description: "UI/UX design, Adobe tools, and modern design trends.",
    overview:
      "This Graphics Design course is crafted to help you unleash your creativity and master visual communication. You will learn essential design principles, color theory, typography, and composition, along with hands-on skills in tools like Adobe Photoshop, Illustrator, and Canva. The course covers creating logos, social media graphics, banners, and other digital assets, enabling you to design professional-quality visuals. By the end, you’ll have a strong portfolio and the confidence to work as a graphic designer in various creative fields.",
    students: 800,
    duration: "3 Months",
    rating: "4.5",
    category: "Designing",
    salary: "₹3–8 LPA",
    tools: ["Adobe Photoshop", "Illustrator", "Canva", "Figma", "InDesign", "XD"],
    roles: ["Graphic Designer", "UI Designer", "Visual Artist", "Brand Identity Designer"],
    image: "https://i.pinimg.com/736x/09/4a/4c/094a4c0e4819a8a359c900027cce633e.jpg",
    syllabus: [
      { title: "Introduction to Graphic Design", description: "Understanding design principles, elements, and tools" },
      { title: "Typography", description: "Fonts, hierarchy, readability, and design with text" },
      { title: "Color Theory", description: "Psychology of colors, color harmony, and palettes" },
      { title: "Adobe Photoshop", description: "Image editing, photo manipulation, and digital artwork" },
      { title: "Adobe Illustrator", description: "Vector graphics, logos, and illustrations" },
      { title: "Layout & Composition", description: "Balance, alignment, grids, and whitespace" },
      { title: "Branding & Identity Design", description: "Logos, brand guidelines, and visual identity" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id:6 ,
    title: "Digital Marketing",
    description: "Master Digital Marketing from fundamentals to advanced strategies.",
    overview:
      "This Digital Marketing course provides a complete understanding of modern online marketing strategies. You will learn SEO, social media marketing, email campaigns, content marketing, PPC advertising, and analytics tools to measure performance. The course combines theory with practical projects, enabling you to create effective marketing campaigns, grow online presence, and drive business results. By the end, you’ll be equipped to plan, execute, and optimize digital marketing strategies like a professional.",
    students: 950,
    duration: "3 Months",
    rating: "4.7",
    category: "Digital Marketing",
    salary: "₹4–9 LPA",
    tools: ["Google Ads", "Canva", "Meta Business Suite", "Google Analytics", "Ahrefs", "Mailchimp"],
    roles: ["Digital Marketer", "SEO Specialist", "Content Strategist", "Social Media Manager"],
    image:
      "https://i.pinimg.com/736x/10/53/a2/1053a2c88fc1c0dd85905a18b3e580da.jpg",
    syllabus: [
      { title: "Introduction to Digital Marketing", description: "Introduction to Digital Marketing – ecosystem, trends, and strategy" },
      { title: "Traditional vs. Digital Marketing", description: "Understanding the evolution of marketing" },
      { title: "Website Planning & Development", description: "Domains, hosting, WordPress, and no-code tools" },
      { title: "SEO", description: "On-page, off-page, and technical SEO" },
      { title: "Social Media Marketing", description: "Facebook, Instagram, LinkedIn, YouTube advertising" },
      { title: "Content Marketing", description: "Blogging, videos, infographics, and storytelling" },
      { title: "Google Analytics 4 (GA4)", description: "Goals, events, and conversion tracking" },
      { title: "Capstone Project", description: "Design and execute a real campaign" },
    ],
    createdAt: "2025-08-28T01:03:09.000Z",
  },
  {
    id: 7,
    title: "Cybersecurity Essentials",
    description:
      "Gain hands-on skills in cybersecurity fundamentals, threats, risk management, cryptography, and incident response.",
    overview:
      "The Cybersecurity Essentials course is designed to provide a solid foundation in protecting digital systems and data. You will learn key concepts such as network security, threat detection, encryption, ethical hacking, and risk management. The course includes hands-on exercises and real-world scenarios to help you understand vulnerabilities and implement effective security measures. By the end, you will have the skills to safeguard information systems and pursue further specialization in cybersecurity.",
    students: 870,
    duration: "3 Months",
    rating: "4.8",
    category: "Cyber",
    salary: "₹6–14 LPA",
    tools: ["Wireshark", "Kali Linux", "Metasploit", "Burp Suite", "Nmap", "Splunk"],
    roles: ["Cybersecurity Analyst", "Ethical Hacker", "Network Security Engineer", "SOC Analyst"],
    image: "https://i.pinimg.com/1200x/44/d0/31/44d031d450d26ceb468aa57fdd0222ba.jpg",
    syllabus: [
      { title: "Introduction to Cybersecurity", description: "Principles and core concepts of cybersecurity" },
      { title: "Cyber Threats and Attack Types", description: "Understanding malware, phishing, ransomware" },
      { title: "Scanning and Vulnerability Assessment", description: "Techniques and tools for scanning networks" },
      { title: "Incident Response", description: "Detecting, managing, and mitigating security breaches" },
      { title: "Cryptography Fundamentals", description: "Encryption, decryption, symmetric/asymmetric keys" },
      { title: "System and Network Hardening", description: "Securing servers and network devices" },
    ],
    createdAt: "2025-08-28T23:03:09.000Z",
  },
  {
    id: 8,
    title: "Game Development in Python",
    description: "Build real-world games using Python libraries like Pygame.",
    overview:
      "This Game Development in Python course teaches you how to create engaging 2D and interactive games using Python and popular libraries like Pygame. You will learn programming fundamentals, game mechanics, animation, collision detection, and user input handling, along with tips for designing fun and playable games. Through hands-on projects, you will build complete games from scratch, gaining practical experience and a portfolio to showcase your game development skills.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Game Development",
    salary: "₹4–8 LPA",
    tools: ["Python", "Pygame", "Blender", "Unity (basics)", "Git"],
    roles: ["Game Developer", "Python Developer", "Indie Game Creator", "Gameplay Programmer"],
    image: "https://i.pinimg.com/736x/3a/b9/d6/3ab9d65eeb5e558bda390a9fd998a700.jpg",
    syllabus: [
      { title: "Introduction to Game Development", description: "Understanding game design principles" },
      { title: "Python Fundamentals for Gaming", description: "Learn Python syntax and logic for games" },
      { title: "Getting Started with Pygame", description: "Introduction to Pygame library" },
      { title: "Game Mechanics & Controls", description: "Handling keyboard/mouse inputs, collisions" },
      { title: "Graphics, Animation & Sound", description: "Integrating sprites, backgrounds, and audio" },
      { title: "Mini Projects", description: "Build games like Snake, Flappy Bird, or Space Shooter" },
      { title: "Game Deployment", description: "Exporting games as executables" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
    id: 9,
    title: "Software Development",
    description: "Master the art of building scalable, efficient software systems.",
    overview:
      "The Software Development course provides a complete foundation for building modern software applications. You will learn programming fundamentals, software design principles, development methodologies, debugging, and testing. The course also covers both frontend and backend development, databases, and version control, giving you the practical skills to create efficient, scalable, and maintainable software. By the end, you’ll be prepared to develop real-world applications and start your career as a software developer.",
    students: 1200,
    duration: "4 Months",
    rating: "4.8",
    category: "Software Development",
    salary: "₹6–12 LPA",
    tools: ["Python", "Java", "Git", "MySQL", "VS Code", "Docker", "Postman"],
    roles: ["Software Developer", "Application Developer", "Backend Engineer", "Junior Software Engineer"],

    image: "https://i.pinimg.com/736x/49/40/6f/49406f1fb7bf3769cb322f3ba2692732.jpg",
    syllabus: [
      { title: "Programming Fundamentals", description: "Core programming concepts and logic building" },
      { title: "Software Design", description: "OOPs, design patterns, and best practices" },
      { title: "Frontend & Backend Development", description: "End-to-end app creation and integration" },
      { title: "Testing & Debugging", description: "Automated testing and bug resolution" },
      { title: "Database & APIs", description: "Working with relational databases and REST APIs" },
      { title: "Version Control & Deployment", description: "Git, CI/CD, and application deployment" },
    ],
    createdAt: "2025-08-27T14:03:09.000Z",
  },
  {
  id: 10,
  title: "Civil AutoCAD",
  description: "Master Civil AutoCAD to design and draft precise civil engineering plans and infrastructure layouts.",
  overview:
    "The Civil AutoCAD Design & Drafting course is tailored for civil engineers, architects, and designers who want to create professional 2D drawings and 3D models for civil projects. You’ll learn survey data interpretation, contour mapping, road alignment, drainage design, and structural detailing. The course also covers drafting standards used in real-world civil projects, including site plans, road layouts, and structural blueprints. By the end, you’ll be proficient in creating accurate civil engineering drawings for residential, commercial, and infrastructure developments.",
  students: 950,
  duration: "3 Months",
  rating: "4.7",
  category: "CAD",
  salary: "₹4–12 LPA",
  tools: ["AutoCAD Civil 3D", "Revit (Basics)", "SketchUp", "InfraWorks"],
  roles: ["Civil CAD Engineer", "Structural Draftsman", "Site Design Engineer", "Infrastructure Planner"],
  
  image: "https://i.pinimg.com/736x/67/4d/2e/674d2e2dab1467c6b473abac456f9a22.jpg",
  syllabus: [
    { title: "Introduction to Civil AutoCAD", description: "Understanding interface, drawing setup, and templates for civil design" },
    { title: "Survey & Site Drafting", description: "Working with survey data, coordinates, and topographical mapping" },
    { title: "Road & Drainage Layouts", description: "Designing roads, pavements, and drainage networks" },
    { title: "Structural Drafting", description: "Creating foundation, column, beam, and slab drawings" },
    { title: "Contour & Grading Plans", description: "Generating contours, grading, and slope analysis" },
    { title: "3D Terrain Modeling", description: "Building 3D surfaces, sections, and civil visualization" }
  ],
  createdAt: "2025-08-27T14:03:09.000Z",
},
{
  id: 11,
  title: "Mobile App Development with React Native",
  description: "Build Android & iOS apps using JavaScript, React Native, and modern backend APIs.",
  overview:
    "This course trains you to become a professional mobile developer using React Native, Firebase, and Node.js. You will learn UI components, navigation, state management, API integration, authentication, push notifications, and app publishing. The course includes real-world app projects like e-commerce, learning app, and real estate app. By the end, you will confidently build and deploy apps to Play Store & App Store.",
  students: 1050,
  duration: "5 Months",
  rating: "4.9",
  category: "Mobile App Development",
  salary: "₹5–14 LPA",
  tools: ["React Native", "CLI", "Redux", "Node.js", "Firebase", "MySQL", "Git", "Figma"],
  roles: [
    "React Native Developer",
    "Mobile App Developer",
    "Frontend Engineer",
    "Cross-Platform App Developer"
  ],
  
  image: "https://i.pinimg.com/736x/2a/c2/df/2ac2df926a0c8b64beb9f5d38c957e3e.jpg",
  syllabus: [
    { title: "React & JavaScript Essentials", description: "JS fundamentals, ES6, React basics" },
    { title: "React Native UI & Navigation", description: "UI components, styling, navigation stack/tabs" },
    { title: "Backend & API Integration", description: "REST API, Axios, Node.js basics, MySQL CRUD" },
    { title: "Authentication & Firebase", description: "JWT login, OTP, Firebase Auth & Firebase DB" },
    { title: "Advanced App Features", description: "Push notifications, maps, camera, storage, animations" },
    { title: "App Deployment", description: "Play Store & App Store deployment, versioning, OTA updates" }
  ],
  createdAt: "2025-08-27T14:03:09.000Z",
},
{
  id: 13,
  title: "UI/UX Design",
  description: "Master UI/UX Design to create user-centered, visually engaging, and seamless digital experiences for web and mobile apps.",
  overview:
    "The UI/UX Design course is crafted for aspiring designers, developers, and creatives who want to build professional interfaces and intuitive user experiences. You’ll learn the fundamentals of user research, wireframing, prototyping, usability testing, and visual design principles. The course covers modern tools like Figma and Adobe XD, real-world project workflows, and portfolio development. By the end, you’ll be able to design responsive, accessible, and aesthetically appealing interfaces for digital products.",
  students: 1020,
  duration: "4 Months",
  rating: "4.8",
  category: "Designing",
  salary: "₹5–15 LPA",
  tools: ["Figma", "Adobe XD", "Miro", "Notion", "Photoshop", "Illustrator"],
  roles: ["UI/UX Designer", "Product Designer", "Interaction Designer", "Visual Designer", "UX Researcher"],
  
  image: "https://i.pinimg.com/736x/04/02/83/040283c30bc220c5816e89dbce1d5869.jpg",
  syllabus: [
    { title: "Introduction to UI/UX Design", description: "Understanding design thinking, user experience principles, and workflows" },
    { title: "User Research & Personas", description: "Conducting interviews, surveys, and creating user personas & empathy maps" },
    { title: "Wireframing & Prototyping", description: "Building low-fidelity wireframes and interactive prototypes using Figma" },
    { title: "Visual Design & Components", description: "Typography, color theory, grids, icons, and creating consistent UI systems" },
    { title: "Usability Testing & Feedback", description: "Testing prototypes with users and refining designs based on insights" },
    { title: "Portfolio & Case Studies", description: "Documenting projects, building a portfolio, and preparing for UI/UX interviews" }
  ],
  createdAt: "2025-08-27T14:03:09.000Z",
}],

   workshops: [
    {
      id: 1,
      title: "Data Analysis",
      description: "Your Fast Track to a High-Demand Career!",
      image: "https://i.pinimg.com/736x/95/fe/7a/95fe7a6efd8ed2054a5552dda2d78731.jpg",
      registered: "80K+ Registered",
      rating: "4.5",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 2,
      title: "React Native Mobile App",
      description: "Learn to build cross-platform mobile apps with React Native.",
      image: "https://i.pinimg.com/1200x/67/1d/a9/671da94427384c7167652c8b5c306c46.jpg",
      registered: "50K+ Registered",
      rating: "4.8",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
    {
      id: 3,
      title: "UI/UX Design",
      description: "Master the fundamentals of UI/UX and create stunning interfaces.",
      image: "https://www.almondsolutions.com/images/blog-ui-ux-150223.jpg",
      registered: "70K+ Registered",
      rating: "4.7",
      price: "99.00",
      old_price: "299.00",
      button_text: "Register Now",
    },
  ],
  

  mentors: [
    {
      id: 3,
      name: "Pranav Swaroop",
      role: "Cyber Security",
      image: "https://i.postimg.cc/brPCnxkr/IMG-20251025-194531-757.webp",
      linkedin: "https://www.linkedin.com/in/pranav-swaroop-75671317?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ",
    },
    {
      id: 4,
      name: "Vasudha",
      role: "Data Analysis",
      image: "https://i.postimg.cc/pLNdNyfz/dha-removebg-preview.png",
      linkedin: "#",
    },
    {
      id: 5,
      name: "Shanthini",
      role: "MERN Stack",
      image: "https://i.postimg.cc/dV36rgL0/Shan.jpg",
      linkedin: "#",
    },
    {
      id: 6,
      name: "Hari Prasadh",
      role: "Digital Marketing",
      image: "https://i.postimg.cc/6pqcnFy4/Harrii.jpg",
      linkedin: "#",
    },
    {
      id: 7,
      name: "Priya Dharshini",
      role: "Python Full Stack",
      image: "https://i.postimg.cc/YqZg4PjR/priya.jpg",
      linkedin: "#",
    },
    {
      id: 8,
      name: "Karthik Raja",
      role: "Cybersecurity Essentials",
      image: "https://i.postimg.cc/BQTvDYbM/karthik.jpg",
      linkedin: "#",
    },
    {
      id: 9,
      name: "Divya Lakshmi",
      role: "Graphics Design",
      image: "https://i.postimg.cc/76L0zdw5/divya.jpg",
      linkedin: "#",
    },
    {
      id: 10,
      name: "Vignesh Kumar",
      role: "Game Development in Python",
      image: "https://i.postimg.cc/HnmJc6vP/vignesh.jpg",
      linkedin: "#",
    },
    {
      id: 11,
      name: "Monisha",
      role: "Software Development",
      image: "https://i.postimg.cc/g0WkJ2fK/monisha.jpg",
      linkedin: "#",
    },
    {
      id: 12,
      name: "Sathish Kumar",
      role: "MERN Stack",
      image: "https://i.postimg.cc/X7CnG0fM/sathish.jpg",
      linkedin: "#",
    },
  ],
};

const courseSlice = createSlice({
  name: "courses",
  initialState,
  reducers: {
    addCourse: (state, action) => {
      state.courses.push(action.payload);
    },
    addWorkshop: (state, action) => {
      state.workshops.push(action.payload);
    },
  },
});

export const { addCourse, addWorkshop } = courseSlice.actions;
export default courseSlice.reducer;